#!/bin/sh
# Graph-store git-push SSH setup (ADR-014). The graph-store repo at /srv/graph-store pushes to
# GitHub over SSH from inside this container. The deploy key generated by provision.sh is
# bind-mounted READ-ONLY and owned by the host 'deploy' user — but OpenSSH refuses a private key
# owned by a uid that is neither root nor the caller, so copy it to a root-owned 0600 path.
# GitHub's published host key is pinned so host verification is strict (no accept-new / no MITM window).
#
# No-op when the key isn't mounted (fresh box before provisioning): the graph-store push then
# degrades to best-effort local commits exactly as designed (ADR-014 §5) — the service still starts.
set -e

KEY_SRC=/run/graph_store_deploy_key
if [ -f "$KEY_SRC" ]; then
  mkdir -p /root/.ssh
  chmod 700 /root/.ssh
  install -m 600 "$KEY_SRC" /root/.ssh/graph_store_deploy_key
  # GitHub's published Ed25519 host key. If GitHub ever rotates it, update this one line.
  printf '%s\n' \
    'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' \
    > /root/.ssh/known_hosts
  chmod 600 /root/.ssh/known_hosts
  git config --global core.sshCommand \
    "ssh -i /root/.ssh/graph_store_deploy_key -o IdentitiesOnly=yes -o UserKnownHostsFile=/root/.ssh/known_hosts -o StrictHostKeyChecking=yes"
fi

exec "$@"
